### ISSUE TITLE
OpenApi string field with format date has bad path in generated typescript

### ISSUE THREAD

**Issue by bhoudu** [devexperts/swagger-codegen-ts#117]
There is an error on the path generated :

    import { DateFromISODateStringIO } from '../utils/utils';

And it should be :

    import { DateFromISODateStringIO } from '../../utils/utils';

**Comment by bhoudu** [comment]
After toying with quick fixes, it seems, DateFromISODateStringIO should not be generated at all in utils.

I feel the io-ts implementation is what is required :

    import { DateFromISOString } from 'io-ts-types/lib/DateFromISOString'

**Comment by Lonelind** [comment]
> After toying with quick fixes, it seems, DateFromISODateStringIO should not be generated at all in utils.
> 
> I feel the io-ts implementation is what is required :
> 
> ```
> import { DateFromISOString } from 'io-ts-types/lib/DateFromISOString'
> ```

The `DateFromISODateStringIO` codec was made to accommodate the specified [`date`](https://swagger.io/docs/specification/data-models/data-types/) data type instead of `date-time` which is covered by `io-ts`'s `DateFromISOString`.

The reason is that the `Date` object in JS always represents date-time. There is no specific object which would work with dates separately but the `Date(year, month, day)` constructor which omits the time information that will always be present if you try to create a `Date` instance using ISO string constructor. Specifically, if you don't specify the time it will be set as `00:00` UTC which is not the desired behavior when you work with dates only. 

The `DateFromISOString` codec, on the other hand, always uses ISO constructor and can't be used to represent the `date` data type because of the described behavior.
